// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0-devel
// 	protoc        v3.19.4
// source: rpcprotos/go_server.proto

package rpcprotos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account  string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *LoginParam) Reset() {
	*x = LoginParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcprotos_go_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginParam) ProtoMessage() {}

func (x *LoginParam) ProtoReflect() protoreflect.Message {
	mi := &file_rpcprotos_go_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginParam.ProtoReflect.Descriptor instead.
func (*LoginParam) Descriptor() ([]byte, []int) {
	return file_rpcprotos_go_server_proto_rawDescGZIP(), []int{0}
}

func (x *LoginParam) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *LoginParam) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ServerToClientMsgResultParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	MsgId   int32  `protobuf:"varint,2,opt,name=msgId,proto3" json:"msgId,omitempty"`
	Content string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *ServerToClientMsgResultParam) Reset() {
	*x = ServerToClientMsgResultParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcprotos_go_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerToClientMsgResultParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerToClientMsgResultParam) ProtoMessage() {}

func (x *ServerToClientMsgResultParam) ProtoReflect() protoreflect.Message {
	mi := &file_rpcprotos_go_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerToClientMsgResultParam.ProtoReflect.Descriptor instead.
func (*ServerToClientMsgResultParam) Descriptor() ([]byte, []int) {
	return file_rpcprotos_go_server_proto_rawDescGZIP(), []int{1}
}

func (x *ServerToClientMsgResultParam) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ServerToClientMsgResultParam) GetMsgId() int32 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *ServerToClientMsgResultParam) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type GoBaseResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *GoBaseResult) Reset() {
	*x = GoBaseResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcprotos_go_server_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoBaseResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoBaseResult) ProtoMessage() {}

func (x *GoBaseResult) ProtoReflect() protoreflect.Message {
	mi := &file_rpcprotos_go_server_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoBaseResult.ProtoReflect.Descriptor instead.
func (*GoBaseResult) Descriptor() ([]byte, []int) {
	return file_rpcprotos_go_server_proto_rawDescGZIP(), []int{2}
}

func (x *GoBaseResult) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GoBaseResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_rpcprotos_go_server_proto protoreflect.FileDescriptor

var file_rpcprotos_go_server_proto_rawDesc = []byte{
	0x0a, 0x19, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x67, 0x6f, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x72, 0x70, 0x63,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x22, 0x42, 0x0a, 0x0a, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x62, 0x0a, 0x1c, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x54, 0x6f, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x73, 0x67, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d,
	0x73, 0x67, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x3c,
	0x0a, 0x0c, 0x47, 0x6f, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0xb6, 0x01, 0x0a,
	0x14, 0x47, 0x6f, 0x52, 0x70, 0x63, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x66, 0x61, 0x63, 0x65, 0x12, 0x3b, 0x0a, 0x07, 0x49, 0x4d, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x12, 0x15, 0x2e, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x1a, 0x17, 0x2e, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2e, 0x47, 0x6f, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x22, 0x00, 0x12, 0x61, 0x0a, 0x1b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x6f, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x27, 0x2e, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x54, 0x6f, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x73, 0x67, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x1a, 0x17, 0x2e, 0x72, 0x70, 0x63,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x47, 0x6f, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x22, 0x00, 0x42, 0x44, 0x0a, 0x20, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x75, 0x69,
	0x74, 0x79, 0x6b, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x61, 0x70, 0x70, 0x69, 0x6d, 0x2e, 0x67,
	0x6f, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0x0a, 0x47, 0x6f, 0x52, 0x70, 0x63,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x0c, 0x2e, 0x2f, 0x3b, 0x72, 0x70, 0x63, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0xa2, 0x02, 0x03, 0x47, 0x52, 0x50, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_rpcprotos_go_server_proto_rawDescOnce sync.Once
	file_rpcprotos_go_server_proto_rawDescData = file_rpcprotos_go_server_proto_rawDesc
)

func file_rpcprotos_go_server_proto_rawDescGZIP() []byte {
	file_rpcprotos_go_server_proto_rawDescOnce.Do(func() {
		file_rpcprotos_go_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpcprotos_go_server_proto_rawDescData)
	})
	return file_rpcprotos_go_server_proto_rawDescData
}

var file_rpcprotos_go_server_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_rpcprotos_go_server_proto_goTypes = []interface{}{
	(*LoginParam)(nil),                   // 0: rpcprotos.LoginParam
	(*ServerToClientMsgResultParam)(nil), // 1: rpcprotos.ServerToClientMsgResultParam
	(*GoBaseResult)(nil),                 // 2: rpcprotos.GoBaseResult
}
var file_rpcprotos_go_server_proto_depIdxs = []int32{
	0, // 0: rpcprotos.GoRpcServerInterface.IMLogin:input_type -> rpcprotos.LoginParam
	1, // 1: rpcprotos.GoRpcServerInterface.ServerToClientMessageResult:input_type -> rpcprotos.ServerToClientMsgResultParam
	2, // 2: rpcprotos.GoRpcServerInterface.IMLogin:output_type -> rpcprotos.GoBaseResult
	2, // 3: rpcprotos.GoRpcServerInterface.ServerToClientMessageResult:output_type -> rpcprotos.GoBaseResult
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpcprotos_go_server_proto_init() }
func file_rpcprotos_go_server_proto_init() {
	if File_rpcprotos_go_server_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpcprotos_go_server_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcprotos_go_server_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerToClientMsgResultParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcprotos_go_server_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoBaseResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpcprotos_go_server_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpcprotos_go_server_proto_goTypes,
		DependencyIndexes: file_rpcprotos_go_server_proto_depIdxs,
		MessageInfos:      file_rpcprotos_go_server_proto_msgTypes,
	}.Build()
	File_rpcprotos_go_server_proto = out.File
	file_rpcprotos_go_server_proto_rawDesc = nil
	file_rpcprotos_go_server_proto_goTypes = nil
	file_rpcprotos_go_server_proto_depIdxs = nil
}
